function adbcode = f_iso2_to_adbmrio(iso2)
% This function converts standard ISO-2 country codes to ADB MRIO country code
% (please note that it is different from ISO-3 for some countries)

iso2cell = {'AU','AT','BD','BE','BT','BR','BN','BG','KH','CA','HR',...
    'CY','CZ','DK','EE','FJ','FI','FR','DE','GR','HK','HU','IN','ID',...
    'IE','IT','JP','KZ','KG','LA','LV','LT','LU','MY','MV','MT',...
    'MX','MN','NP','NL','NO','PK','CN','PH','PL','PT','KR','RO','RU',...
    'SG','SK','SI','ES','LK','SE','CH','TW','TH','TR','GB','US','VN'};

% iso3cell = {'AUS','AUT','BGD','BEL','BTN','BRA','BRN','BGR','KHM','CAN','HRV',...
%     'CYP','CZE','DNK','EST','FJI','FIN','FRA','DEU','GRC','HKG','HUN','IND','IDN',...
%     'IRL','ITA','JPN','KAZ','KGZ','LAO','LVA','LTU','LUX','MYS','MDV','MLT',...
%     'MEX','MNG','NPL','NLD','NOR','PAK','CHN','PHL','POL','PRT','KOR','ROU','RUS',...
%     'SGP','SVK','SVN','ESP','LKA','SWE','CHE','TWN','THA','TUR','GBR','USA','VNM'};

adbcell = {'AUS','AUT','BAN','BEL','BHU','BRA','BRU','BGR','CAM','CAN','HRV',...
    'CYP','CZE','DEN','EST','FIJ','FIN','FRA','GER','GRC','HKG','HUN','IND','INO',...
    'IRE','ITA','JPN','KAZ','KGZ','LAO','LVA','LTU','LUX','MAL','MLD','MLT',...
    'MEX','MON','NEP','NET','NOR','PAK','PRC','PHI','POL','POR','KOR','ROM','RUS',...
    'SIN','SVK','SVN','SPA','SRI','SWE','SWI','TAP','THA','TUR','UKG','USA','VIE'};

adbcode = adbcell(strcmp(iso2,iso2cell));

end
