function oecdcode = f_iso2_to_oecdicio(iso2)
% This function converts standard ISO-2 country codes to ISO-3 codes used in OECD ICIO

iso2cell = {'AR','AU','AT','BE','BD','BG','BY','BR','BN','CA','CH','CL','CN',...
    'CI','CM','CO','CR','CY','CZ','DE','DK','EG','ES','EE','FI','FR','GB','GR',...
    'HK','HR','HU','ID','IN','IE','IS','IL','IT','JO','JP','KZ','KH','KR','LA',...
    'LT','LU','LV','MA','MX','MT','MM','MY','NG','NL','NO','NZ','PK','PE',...
    'PH','PL','PT','RO','RU','SA','SN','SG','SK','SI','SE','TH','TN','TR',...
    'TW','UA','US','VN','ZA'};

oecdcell = {'ARG','AUS','AUT','BEL','BGD','BGR','BLR','BRA','BRN','CAN','CHE','CHL','CHN',...
    'CIV','CMR','COL','CRI','CYP','CZE','DEU','DNK','EGY','ESP','EST','FIN','FRA','GBR','GRC',...
    'HKG','HRV','HUN','IDN','IND','IRL','ISL','ISR','ITA','JOR','JPN','KAZ','KHM','KOR','LAO',...
    'LTU','LUX','LVA','MAR','MEX','MLT','MMR','MYS','NGA','NLD','NOR','NZL','PAK','PER',...
    'PHL','POL','PRT','ROU','RUS','SAU','SEN','SGP','SVK','SVN','SWE','THA','TUN','TUR',...
    'TWN','UKR','USA','VNM','ZAF'};

oecdcode = oecdcell(strcmp(iso2,iso2cell));

end
