function [iso2,source] = f_select_country_source()
% This function lists the available countries and source for users along
% with instructions on how to enter these for further use in the codes


%% 1 Country codes
prompt_country = strcat( ...
    "\n-------------------\n", ...
    "\nList of available economies by source:\n", ...
    "  - Asian Development Bank Multi-Regional Input-Output tables (ADB MRIO):\n", ...
    "    AT, AU, BD, BE, BG, BN, BR, BT, CA, CH, CN, CY, CZ, DE, DK, EA, EE, ES, FI, FJ, FR, GB, GR, HK, HR, HU, \n", ...
    "    ID, IE, IN, IT, JP, KG, KH, KR, KZ, LA, LK, LT, LU, LV, MN, MT, MV, MX, MY, NL, NO, NP, PH, PK, PL, PT, \n", ...
    "    RO, RU, SE, SG, SI, SK, TH, TR, TW, US, VN\n", ...
    "  - Organisation for Economic Co-operation and Development Inter-Country Input-Output tables (OECD ICIO): \n", ...
    "    AR, AT, AU, BD, BE, BG, BN, BR, BY, CA, CH, CI, CL, CM, CN, CO, CR, CY, CZ, DE, DK, EA, EE, EG, ES, FI,\n", ...
    "    FR, GB, GR, HK, HR, HU, ID, IE, IL, IN, IS, IT, JO, JP, KH, KR, KZ, LA, LT, LU, LV, MA, MM, MT, MX, MY,\n", ...
    "    NG, NL, NO, NZ, PE, PH, PK, PL, PT, RO, RU, SA, SE, SG, SI, SK, SN, TH, TN, TR, TW, UA, US, VN, ZA\n", ...
    "  - United States Bureau of Economic Analysis Input-Output table (US BEA IO):\n", ...
    "    US\n", ...
    "* Note: EA for the euro area.", ...
    "\nUSER INPUT NEEDED: Enter the two-letter ISO code of the economy of your choice (eg, US) and press `Enter'.\nSee above for the list of available country codes.\n > " ...
    );
iso2 = input(prompt_country, 's');
iso2 = upper(strrep(strrep(iso2, '''', ''), '"', ''));

%% 2 Data sources
adb_cc_list = {...
    'AT', 'AU', 'BD', 'BE', 'BG', 'BN', 'BR', 'BT', 'CA', 'CH', 'CN', 'CY', 'CZ', 'DE', ...
    'DK', 'EA', 'EE', 'ES', 'FI', 'FJ', 'FR', 'GB', 'GR', 'HK', 'HR', 'HU', 'ID', 'IE', ...
    'IN', 'IT', 'JP', 'KG', 'KH', 'KR', 'KZ', 'LA', 'LK', 'LT', 'LU', 'LV', 'MN', 'MT', ...
    'MV', 'MX', 'MY', 'NL', 'NO', 'NP', 'PH', 'PK', 'PL', 'PT', 'RO', 'RU', 'SE', 'SG', ...
    'SI', 'SK', 'TH', 'TR', 'TW', 'US', 'VN'...
    };
bea_cc_list = {'US'};
oecd_cc_list = {...
    'AR', 'AT', 'AU', 'BD', 'BE', 'BG', 'BN', 'BR', 'BY', 'CA', 'CH', 'CI', 'CL', 'CM', 'CN', ...
    'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'EA', 'EE', 'EG', 'ES', 'FI', 'FR', 'GB', 'GR', 'HK', ...
    'HR', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JO', 'JP', 'KH', 'KR', 'KZ', 'LA', 'LT', ...
    'LU', 'LV', 'MA', 'MM', 'MT', 'MX', 'MY', 'NG', 'NL', 'NO', 'NZ', 'PE', 'PH', 'PK', 'PL', ...
    'PT', 'RO', 'RU', 'SA', 'SE', 'SG', 'SI', 'SK', 'SN', 'TH', 'TN', 'TR', 'TW', 'UA', 'US', ...
    'VN', 'ZA'...
    };

%% Check if country code-data source match
if ~ismember(iso2,union(adb_cc_list,oecd_cc_list))
    error(['Error: The country code you entered is either invalid or not included in the available data sources. ' ...
        'Verify the country code from the list provided above and try again. Execution has been stopped.']);

elseif ismember(iso2,union(adb_cc_list,oecd_cc_list))

    % List only data sources that the inputted country is included in
    if ismember(iso2,oecd_cc_list) && ismember(iso2,adb_cc_list) && ismember(iso2,bea_cc_list)
        prompt_source = strcat( ...
            "\n-------------------\n", ...
            "\nList of available sources for ",iso2, ":\n", ...
            "  adb  : Asian Development Bank Multi-Regional Input-Output tables (ADB MRIO)\n", ...
            "  bea  : United States Bureau of Economic Analysis Input-Output table (US BEA IO)\n", ...
            "  oecd : Organisation for Economic Co-operation and Development Inter-Country Input-Output tables (OECD ICIO)\n", ...
            "USER INPUT NEEDED: Enter the abbreviation for the data source of your choice (eg, oecd) and press `Enter'.\nSee above for the list of available abbreviations.\n > " ...
            );

    elseif ismember(iso2,oecd_cc_list) && ismember(iso2,adb_cc_list) && ~ismember(iso2,bea_cc_list)
        prompt_source = strcat( ...
            "\n-------------------\n", ...
            "\nList of available sources for ",iso2, ":\n", ...
            "  adb  : Asian Development Bank Multi-Regional Input-Output tables (ADB MRIO)\n", ...
            "  oecd : Organisation for Economic Co-operation and Development Inter-Country Input-Output tables (OECD ICIO)\n", ...
            "USER INPUT NEEDED: Enter the abbreviation for the data source of your choice (eg, oecd) and press `Enter'.\nSee above for the list of available abbreviations.\n > " ...
            );

    elseif ismember(iso2,oecd_cc_list) && ~ismember(iso2,adb_cc_list) && ~ismember(iso2,bea_cc_list)
        prompt_source = strcat( ...
            "\n-------------------\n", ...
            "\nList of available sources for ",iso2, ":\n", ...
            "  oecd : Organisation for Economic Co-operation and Development Inter-Country Input-Output tables (OECD ICIO)\n", ...
            "USER INPUT NEEDED: Enter the abbreviation for the data source of your choice (eg, oecd) and press `Enter'.\nSee above for the list of available abbreviations.\n > " ...
            );

    elseif ~ismember(iso2,oecd_cc_list) && ismember(iso2,adb_cc_list) && ~ismember(iso2,bea_cc_list)
        prompt_source = strcat( ...
            "\n-------------------\n", ...
            "\nList of available sources for ",iso2, ":\n", ...
            "  adb  : Asian Development Bank Multi-Regional Input-Output tables (ADB MRIO)\n", ...
            "USER INPUT NEEDED: Enter the abbreviation for the data source of your choice (eg, adb) and press `Enter'.\nSee above for the list of available abbreviations.\n > " ...
            );
    end

    % Prompt source
    if exist('prompt_source','var')
        source = input(prompt_source, 's');
        source = strrep(source, '''', '');
        source = strrep(source, '"', '');
        source = lower(source);
        if ~ismember(source, {'adb', 'bea', 'oecd'})
            error(['Error: The data source you entered is invalid or not supported. ' ...
                'Enter a valid data source from the list provided above. Execution has been stopped.']);
        elseif ~ismember(iso2, eval([source '_cc_list']))
            error(['Error: The selected data source (%s) does not include the entered country code (%s). ' ...
                'Enter a data source that supports the provided country code from the list above. Execution has been stopped.'], source, iso2);
        end
    end
end

end